// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: sync.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DelAccClient is the client API for DelAcc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DelAccClient interface {
	Do(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type delAccClient struct {
	cc grpc.ClientConnInterface
}

func NewDelAccClient(cc grpc.ClientConnInterface) DelAccClient {
	return &delAccClient{cc}
}

func (c *delAccClient) Do(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.DelAcc/Do", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DelAccServer is the server API for DelAcc service.
// All implementations must embed UnimplementedDelAccServer
// for forward compatibility
type DelAccServer interface {
	Do(context.Context, *Request) (*Response, error)
	
}

// UnimplementedDelAccServer must be embedded to have forward compatible implementations.
type UnimplementedDelAccServer struct {
}

func (UnimplementedDelAccServer) Do(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Do not implemented")
}
func (UnimplementedDelAccServer) mustEmbedUnimplementedDelAccServer() {}

// UnsafeDelAccServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DelAccServer will
// result in compilation errors.
type UnsafeDelAccServer interface {
	mustEmbedUnimplementedDelAccServer()
}

func RegisterDelAccServer(s grpc.ServiceRegistrar, srv DelAccServer) {
	s.RegisterService(&DelAcc_ServiceDesc, srv)
}

func _DelAcc_Do_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DelAccServer).Do(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DelAcc/Do",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DelAccServer).Do(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// DelAcc_ServiceDesc is the grpc.ServiceDesc for DelAcc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DelAcc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DelAcc",
	HandlerType: (*DelAccServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Do",
			Handler:    _DelAcc_Do_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sync.proto",
}
